import mongoose from 'mongoose';

const { ObjectId } = mongoose.Schema.Types;

export const MESSAGE_TYPES = ['text', 'image', 'video', 'audio', 'voice', 'file', 'system'];

const mediaSchema = new mongoose.Schema(
  {
    url: { type: String, required: true },
    name: String,
    size: Number,
    mime: String,
    duration: Number,
    width: Number,
    height: Number,
  },
  { _id: false }
);

const messageSchema = new mongoose.Schema(
  {
    conversation: { type: ObjectId, ref: 'Conversation', required: true },
    sender: { type: ObjectId, ref: 'User', default: null }, // null for system messages
    // Generated by the client so retries after a reconnect never create duplicates.
    clientId: { type: String },
    type: { type: String, enum: MESSAGE_TYPES, default: 'text' },
    text: { type: String, maxlength: 10000, default: '' },
    media: { type: mediaSchema, default: undefined },
    replyTo: { type: ObjectId, ref: 'Message', default: null },
    forwarded: { type: Boolean, default: false },
    reactions: [{ _id: false, user: { type: ObjectId, ref: 'User' }, emoji: String }],
    starredBy: [{ type: ObjectId, ref: 'User' }],
    deletedFor: [{ type: ObjectId, ref: 'User' }],
    deletedForEveryone: { type: Boolean, default: false },
    editedAt: { type: Date, default: null },
    expiresAt: { type: Date, default: undefined },
  },
  { timestamps: true }
);

messageSchema.index({ conversation: 1, createdAt: -1 });
messageSchema.index(
  { sender: 1, clientId: 1 },
  { unique: true, partialFilterExpression: { clientId: { $type: 'string' } } }
);
// Disappearing messages: MongoDB removes documents once expiresAt passes.
messageSchema.index({ expiresAt: 1 }, { expireAfterSeconds: 0 });

export const Message = mongoose.models.Message || mongoose.model('Message', messageSchema);
